version: '3.7'

networks:
  BOT:

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - "DOTNET_ENVIRONMENT=Production"
    depends_on:
      - web
    networks:
      - BOT
  web:
    build: 
      context: .
      dockerfile: DockerfileWeb
    container_name: web
    restart: unless-stopped
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_ENVIRONMENT=Production"
    ports: 
      - "5000:80"
      - "5001:443"
    networks:
      - BOT